language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r nagagu *
  - mkdir -p deploy
  - mv nagagu.zip deploy/nagagu.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: boot-web-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-delpoyed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: boot-web-build
    key: nagagu.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: nagagu-deploy # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: nagagu-deploy-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true

before_install:
  - chmod +x gradlew

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - hwanghkt@gmail.com
